config/routes.rb
Omrails::Application.routes.draw do
  devise_for :users

 get 'abouts' => 'page#abouts'

root :to => 'page#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<!--	<a href="http://www.google.com" >cerca qui</a> -->
		<%= link_to "cerca qui", "http://www.google.com" %>
		... by <%= link_to "Loretta", "http://it.linkedin.com/pub/loretta-diana/53/35b/b72" %>
	</small>

</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "My first", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
				<ul class="nav">
      		<li> <%= link_to "Home", root_path %></li>
					<li><%= link_to "About", abouts_path %></li>
				</ul>
				<ul class="nav pull-right">
          <% if user_signed_in?%>
           <li> <%= link_to "Edit Profile",  edit_user_registration_path %></li>
            <li> <%= link_to "Logout",  destroy_user_session_path, method: :delete %></li>
          <% else %>
      		  <li> <%= link_to "Login",  new_user_session_path %></li>
          <% end %>
				</ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>provaRubyOnRails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= render "layouts/header" %>
		<div class="container">
			<% flash.each do |name,msg| %>
				<% content_tag(:div,msg,class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render "layouts/footer" %>
		</div>
	</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/abouts.html.erb
<h1> About Page</h1>
<p>
	<%= link_to "link al meteo", "www.ilmeteo.it" %>
	per sapere le previsioni,  
	<%= link_to "dove", "https://maps.google.com/" %>
	e quando
</p>

app/views/page/home.html.erb
<!-- <div class="row">
  <div class="span4">
  	<h2> Navigation Bar </h2>
  </div>
  <div class="span8"> -->

<% if user_signed_in?%>
	<div class="hero-unit">
  	<h1> This is Your private Home page </h1>
	</div>
<% else %>
	<div class="hero-unit">
	  	<h1>Welcome to my first Page!</h1>
			<p>
				da qui puoi cercare quello che vuoi
			<!--	<a href="http://www.google.com" >cerca qui</a> -->
			<%= link_to "cerca qui...", "http://www.google.com" %>
				e trovi ciò che vuoi
			</p>
			<p>
				<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-primary btn-large" %> 
				<!--<a href="#"> Sign up now!</a> -->
			</p>
	</div>

<% end %>

  <!-- </div>
</div>  -->